deploy:
  path: backend/Carhub-backend
  environment:
    - APP_ENV=production
    - APP_KEY=base64:h9Ea+2dGd9/h02RNCq8zMpQ6Nc9aL9fGc/HXUQ3hC7s=
    - APP_DEBUG=false
    - APP_URL=https://carhub.com
    - DB_CONNECTION=mysql
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_DATABASE=carhub
    - DB_USERNAME=root
    - DB_PASSWORD=root